services:
  app-service:
    image: mattymatiman/app-service # specify name of image on Docker Hub
    restart: "always" # automatically restart container when server crashes
    environment: # set up environment variables
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost} # Use localhost as the default value
    ports:
      - "8000:8000" # expose port 8000 so that applications outside the container can connect to it
    depends_on: # only run app-service after auth-service has started
      auth-service:
        condition: service_started
  auth-service:
    image: mattymatiman/auth-service
    restart: "always" # automatically restart container when server crashes
    environment:
      JWT_SECRET: ${JWT_SECRET}
      
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@ps-db:5432/db-1"
    ports:
      - "3000:3000" # expose port 3000 so that applications outside the container can connect to it
    depends_on:
      ps-db:
        condition: service_healthy
  ps-db:
    container_name: ps-db
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db-1  # Optional
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local  

